rabbitmq:
  image: rabbitmq:management
  ports:
   - "5672:5672"
   - "15672:15672"
  environment:
   - RABBITMQ_ERLANG_COOKIE=cluster_cookie
   - RABBITMQ_DEFAULT_USER=admin
   - RABBITMQ_DEFAULT_PASS=Admin@123